version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: tyepay_db
    environment:
      POSTGRES_USER: tyecode
      POSTGRES_PASSWORD: tyepay_local_password
      POSTGRES_DB: tyepay
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
